export enum TodoActionTypes {
    LOAD_TODOS = "LOAD_TODOS",
    LOAD_TODOS_COMPLETED = "LOAD_TODOS_COMPLETED",
    OPEN_TODO_DIALOG = "OPEN_TODO_DIALOG",
    CLOSE_DIALOG = "CLOSE_DIALOG",
    FIELD_CHANGE = "FIELD_CHANGE",
    SAVE_CHANGES = "SAVE_CHANGES",
    SAVE_CHANGES_COMPLETED = "SAVE_CHANGES_COMPLETED",
    DELETE_TODO = "DELETE_TODO",
    DELETE_TODO_COMPLETED = "DELETE_TODO_COMPLETED",
    SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY"
}